# Generated by Django 2.1.7 on 2019-04-10 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.FileField(null=True, upload_to='', verbose_name='')),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('publishyear', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
