# Generated by Django 2.1.7 on 2019-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seller',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
